name: ci

on:
  push:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      TEST_HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
      TEST_HUMANITEC_ORG: ${{ secrets.HUMANITEC_ORG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install graph webview dependencies
        working-directory: ./webview/resource-dependency-graph
        run: npm install

      - name: Build graph webview
        working-directory: ./webview/resource-dependency-graph
        run: npm run build

      - run: npm ci
      
      - run: npm run lint
        if: runner.os == 'Linux'

      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - run: npm test
        if: runner.os != 'Linux'

      - if: startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        name: Inject user agent version
        run:
            sed -i "s/VsceVersion = 'unspecified'/VsceVersion = '${{ github.ref_name }}'/g" src/extension.ts

      - name: Validate extension is packable
        if: runner.os == 'Linux'
        run: npx vsce package

      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux'
        run: npx vsce publish ${{ github.ref_name }} --no-git-tag-version
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
